use enumset::{EnumSet, EnumSetType};
use num_derive::FromPrimitive;
use num_traits::FromPrimitive;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug)]
pub struct InputOptions {
    pub auto_reorder: bool,
    pub combi_on_double_stroke: bool,
    pub non_initial_combi: bool,
    pub medial_combi: bool,
    pub treat_final_as_initial: bool,
    pub old_jamo_mode: bool,
    pub noble_name: bool,
}

impl Default for InputOptions {
    fn default() -> Self {
        Self {
            auto_reorder: false,
            combi_on_double_stroke: false,
            non_initial_combi: false,
            medial_combi: true,
            treat_final_as_initial: true,
            old_jamo_mode: false,
            noble_name: false,
        }
    }
}

#[derive(Hash, Serialize, Deserialize, Debug, EnumSetType)]
#[enumset(serialize_repr = "list")]
pub enum Addon {
    ComposeInitialToen,
    ComposeMedialToen,
    ComposeFinalToen,
    DecomposeInitialToen,
    DecomposeMedialToen,
    DecomposeFinalToen,
    FlexibleComposeOrder,
    TreatFinalAsInitial,
    TreatFinalAsInitialCompose,
}

pub fn default_addons() -> EnumSet<Addon> {
    EnumSet::only(Addon::ComposeInitialToen).union(EnumSet::only(Addon::TreatFinalAsInitial))
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq, Default)]
pub enum PreeditJohabLevel {
    Always,
    #[default]
    Needed,
    Never,
}

macro_rules! impl_jamo {
    ($ty:ty, [$(($item:ident, $ch:expr)),+ $(,)?]) => {
        impl $ty {
            pub const fn jamo(self) -> char {
                match self {
                    $(Self::$item => $ch,)+
                }
            }

            pub const fn from_initial_sound(c: char) -> Option<Self> {
                match c {
                    $($ch => Some(Self::$item),)+
                    _ => None,
                }
            }
        }
    };
}

macro_rules! impl_traits {
    ($ty:ty, $first_ch:expr) => {
        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                write!(f, "{}", char::from(*self))
            }
        }

        impl TryFrom<char> for $ty {
            type Error = ();
            fn try_from(ch: char) -> Result<Self, Self::Error> {
                use std::convert::TryInto;
                (ch as u32).try_into()
            }
        }

        impl TryFrom<u32> for $ty {
            type Error = ();
            fn try_from(n: u32) -> Result<Self, Self::Error> {
                match n.checked_sub($first_ch as u32) {
                    Some(idx) => FromPrimitive::from_u32(idx).ok_or(()),
                    None => Err(()),
                }
            }
        }

        impl Serialize for $ty {
            fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                serializer.serialize_char((*self).into())
            }
        }

        impl<'de> Deserialize<'de> for $ty {
            fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                use serde::de::Error;
                use std::convert::TryInto;
                let ch = char::deserialize(deserializer)?;
                ch.try_into()
                    .map_err(|_| D::Error::custom(format!("Not {}", stringify!($ty))))
            }
        }
    };
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, FromPrimitive)]
#[repr(u32)]
pub enum Initial {
    Kiuk,
    ToenKiuk,
    Niun,
    Tiut,
    ToenTiut,
    Riul,
    Mium,
    Piup,
    ToenPiup,
    Siut,
    ToenSiut,
    Iung,
    Jiut,
    ToenJiut,
    Chiut,
    Khiuk,
    Thiut,
    Phiup,
    Hiut,
    NiunKiuk,
    TuNiun,
    NiunTiut,
    NiunPiup,
    TiutKiuk,
    RiulNiun,
    TuRiul,
    RiulHiut,
    KabyounRiul,
    MiumPiup,
    KabyounMium,
    PiupKiuk,
    PiupNiun,
    PiupTiut,
    PiupSiut,
    PiupSiutKiuk,
    PiupSiutTiut,
    PiupSiutPiup,
    PiupTuSiut,
    PiupSiutJiut,
    PiupJiut,
    PiupChiut,
    PiupThiut,
    PiupPhiup,
    KabyounPiup,
    KabyounTuPiup,
    SiutKiuk,
    SiutNiun,
    SiutTiut,
    SiutRiul,
    SiutMium,
    SiutPiup,
    SiutPiupKiuk,
    SiutTuSiut,
    SiutIung,
    SiutJiut,
    SiutChiut,
    SiutKhiuk,
    SiutThiut,
    SiutPhiup,
    SiutHiut,
    ImorisoriSiut,
    ImorisoriTuSiut,
    ImomsoriSiut,
    ImomsoriTuSiut,
    Panisori,
    IungKiuk,
    IungTiut,
    IungMium,
    IungPiup,
    IungSiut,
    IungPanisori,
    TuIung,
    IungJiut,
    IungChiut,
    IungThiut,
    IungPhiup,
    Ogumisori,
    JiutIung,
    ImorisoriJiut,
    ImorisoriTuJiut,
    ImomsoriJiut,
    ImomsoriTuJiut,
    ChiutKhiuk,
    ChiutHiut,
    ImorisoriChiut,
    ImomsoriChiut,
    PhiupPiup,
    KabyounPhiup,
    TuHiut,
    Mokkumongthojimsori,
    KiukTiut,
    NiunSiut,
    NiunJiut,
    NiunHiut,
    TiutRiul,
    TiutMium,
    TiutPiup,
    TiutSiut,
    TiutJiut,
    RiulKiuk,
    RiulTuKiuk,
    RiulTiut,
    RiulTuTiut,
    RiulMium,
    RiulPiup,
    RiulTuPiup,
    RiulKabyounPiup,
    RiulSiut,
    RiulJiut,
    RiulKhiuk,
    MiumKiuk,
    MiumTiut,
    MiumSiut,
    PiupSiutThiut,
    PiupKhiuk,
    PiupHiut,
    TuSiutPiup,
    IungRiul,
    IungHiut,
    TuJiutHiut,
    TuThiut,
    PhiupHiut,
    HiutSiut,
    TuMokkumongthojimsori,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, FromPrimitive)]
#[repr(u32)]
pub enum Medial {
    A,
    Ae,
    Ya,
    Yae,
    Eo,
    E,
    Yeo,
    Ye,
    O,
    Wa,
    Wae,
    Oe,
    Yo,
    U,
    Weo,
    We,
    Wi,
    Yu,
    Eu,
    Yi,
    I,
    AO,
    AU,
    YaO,
    YaYo,
    EoO,
    EoU,
    EoEu,
    YeoO,
    YeoU,
    OEo,
    OE,
    OYe,
    OO,
    OU,
    YoYa,
    YoYae,
    YoYeo,
    YoO,
    YoI,
    UA,
    UAe,
    UEoEu,
    UYe,
    UU,
    YuA,
    YuEo,
    YuE,
    YuYeo,
    YuYe,
    YuU,
    YuI,
    EuU,
    EuEu,
    YiU,
    IA,
    IYa,
    IO,
    IU,
    IEu,
    IAraea,
    Araea,
    AraeaEo,
    AraeaU,
    AraeaI,
    TuAraea,
    AEu,
    YaU,
    YeoYa,
    OYa,
    OYae,
    OYeo,
    OOI,
    YoA,
    YoAe,
    YoEo,
    UYeo,
    UII,
    YuAe,
    YuO,
    EuA,
    EuEo,
    EuE,
    EuO,
    IYaO,
    IYae,
    IYeo,
    IYe,
    IOI,
    IYo,
    IYu,
    II,
    AraeaA,
    AraeaE,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, FromPrimitive)]
#[repr(u32)]
pub enum Final {
    Kiuk,
    ToenKiuk,
    KiukSiut,
    Niun,
    NiunJiut,
    NiunHiut,
    Tiut,
    Riul,
    RiulKiuk,
    RiulMium,
    RiulPiup,
    RiulSiut,
    RiulThiut,
    RiulPhiup,
    RiulHiut,
    Mium,
    Piup,
    PiupSiut,
    Siut,
    ToenSiut,
    Iung,
    Jiut,
    Chiut,
    Khiuk,
    Thiut,
    Phiup,
    Hiut,
    KiukRiul,
    KiukSiutKiuk,
    NiunKiuk,
    NiunTiut,
    NiunSiut,
    NiunPanisori,
    NiunThiut,
    TiutKiuk,
    TiutRiul,
    RiulKiukSiut,
    RiulNiun,
    RiulTiut,
    RiulTiutHiut,
    TuRiul,
    RiulMiumKiuk,
    RiulMiumSiut,
    RiulPiupSiut,
    RiulPiupHiut,
    RiulKabyounPiup,
    RiulTuSiut,
    RiulPanisori,
    RiulKhiuk,
    RiulMokkumongthojimsori,
    MiumKiuk,
    MiumRiul,
    MiumPiup,
    MiumSiut,
    MiumTuSiut,
    MiumPanisori,
    MiumChiut,
    MiumHiut,
    KabyounMium,
    PiupRiul,
    PiupPhiup,
    PiupHiut,
    KabyounPiup,
    SiutKiuk,
    SiutTiut,
    SiutRiul,
    SiutPiup,
    Panisori,
    IungKiuk,
    IungTuKiuk,
    TuIung,
    IungKhiuk,
    Ogumisori,
    OgumisoriSiut,
    OgumisoriPanisori,
    PhiupPiup,
    KabyounPhiup,
    HiutNiun,
    HiutRiul,
    HiutMium,
    HiutPiup,
    Mokkumongthojimsori,
    KiukNiun,
    KiukPiup,
    KiukChiut,
    KiukKhiuk,
    KiukHiut,
    TuNiun,
    NiunRiul,
    NiunChiut,
    TuTiut,
    TuTiutPiup,
    TiutPiup,
    TiutSiut,
    TiutSiutKiuk,
    TiutJiut,
    TiutChiut,
    TiutThiut,
    RiulTuKiuk,
    RiulKiukHiut,
    TuRiulKhiuk,
    RiulMiumHiut,
    RiulPiupTiut,
    RiulPiupPhiup,
    RiulOgumisori,
    RiulMokkumongthojimsoriHiut,
    KabyounRiul,
    MiumNiun,
    MiumTuNiun,
    TuMium,
    MiumPiupSiut,
    MiumJiut,
    PiupTiut,
    PiupRiulPhiup,
    PiupMium,
    TuPiup,
    PiupSiutTiut,
    PiupJiut,
    PiupChiut,
    SiutMium,
    SiutKabyounPiup,
    TuSiutKiuk,
    TuSiutTiut,
    SiutPanisori,
    SiutJiut,
    SiutChiut,
    SiutThiut,
    SiutHiut,
    PanisoriPiup,
    PanisoriKabyounPiup,
    OgumisoriMium,
    OgumisoriHiut,
    JiutPiup,
    JiutTuPiup,
    TuJiut,
    PhiupSiut,
    PhiupThiut,
}

impl From<Initial> for char {
    fn from(c: Initial) -> Self {
        match c {
            Initial::Kiuk => '\u{1100}',
            Initial::ToenKiuk => '\u{1101}',
            Initial::Niun => '\u{1102}',
            Initial::Tiut => '\u{1103}',
            Initial::ToenTiut => '\u{1104}',
            Initial::Riul => '\u{1105}',
            Initial::Mium => '\u{1106}',
            Initial::Piup => '\u{1107}',
            Initial::ToenPiup => '\u{1108}',
            Initial::Siut => '\u{1109}',
            Initial::ToenSiut => '\u{110A}',
            Initial::Iung => '\u{110B}',
            Initial::Jiut => '\u{110C}',
            Initial::ToenJiut => '\u{110D}',
            Initial::Chiut => '\u{110E}',
            Initial::Khiuk => '\u{110F}',
            Initial::Thiut => '\u{1110}',
            Initial::Phiup => '\u{1111}',
            Initial::Hiut => '\u{1112}',
            Initial::NiunKiuk => '\u{1113}',
            Initial::TuNiun => '\u{1114}',
            Initial::NiunTiut => '\u{1115}',
            Initial::NiunPiup => '\u{1116}',
            Initial::TiutKiuk => '\u{1117}',
            Initial::RiulNiun => '\u{1118}',
            Initial::TuRiul => '\u{1119}',
            Initial::RiulHiut => '\u{111A}',
            Initial::KabyounRiul => '\u{111B}',
            Initial::MiumPiup => '\u{111C}',
            Initial::KabyounMium => '\u{111D}',
            Initial::PiupKiuk => '\u{111E}',
            Initial::PiupNiun => '\u{111F}',
            Initial::PiupTiut => '\u{1120}',
            Initial::PiupSiut => '\u{1121}',
            Initial::PiupSiutKiuk => '\u{1122}',
            Initial::PiupSiutTiut => '\u{1123}',
            Initial::PiupSiutPiup => '\u{1124}',
            Initial::PiupTuSiut => '\u{1125}',
            Initial::PiupSiutJiut => '\u{1126}',
            Initial::PiupJiut => '\u{1127}',
            Initial::PiupChiut => '\u{1128}',
            Initial::PiupThiut => '\u{1129}',
            Initial::PiupPhiup => '\u{112A}',
            Initial::KabyounPiup => '\u{112B}',
            Initial::KabyounTuPiup => '\u{112C}',
            Initial::SiutKiuk => '\u{112D}',
            Initial::SiutNiun => '\u{112E}',
            Initial::SiutTiut => '\u{112F}',
            Initial::SiutRiul => '\u{1130}',
            Initial::SiutMium => '\u{1131}',
            Initial::SiutPiup => '\u{1132}',
            Initial::SiutPiupKiuk => '\u{1133}',
            Initial::SiutTuSiut => '\u{1134}',
            Initial::SiutIung => '\u{1135}',
            Initial::SiutJiut => '\u{1136}',
            Initial::SiutChiut => '\u{1137}',
            Initial::SiutKhiuk => '\u{1138}',
            Initial::SiutThiut => '\u{1139}',
            Initial::SiutPhiup => '\u{113A}',
            Initial::SiutHiut => '\u{113B}',
            Initial::ImorisoriSiut => '\u{113C}',
            Initial::ImorisoriTuSiut => '\u{113D}',
            Initial::ImomsoriSiut => '\u{113E}',
            Initial::ImomsoriTuSiut => '\u{113F}',
            Initial::Panisori => '\u{1140}',
            Initial::IungKiuk => '\u{1141}',
            Initial::IungTiut => '\u{1142}',
            Initial::IungMium => '\u{1143}',
            Initial::IungPiup => '\u{1144}',
            Initial::IungSiut => '\u{1145}',
            Initial::IungPanisori => '\u{1146}',
            Initial::TuIung => '\u{1147}',
            Initial::IungJiut => '\u{1148}',
            Initial::IungChiut => '\u{1149}',
            Initial::IungThiut => '\u{114A}',
            Initial::IungPhiup => '\u{114B}',
            Initial::Ogumisori => '\u{114C}',
            Initial::JiutIung => '\u{114D}',
            Initial::ImorisoriJiut => '\u{114E}',
            Initial::ImorisoriTuJiut => '\u{114F}',
            Initial::ImomsoriJiut => '\u{1150}',
            Initial::ImomsoriTuJiut => '\u{1151}',
            Initial::ChiutKhiuk => '\u{1152}',
            Initial::ChiutHiut => '\u{1153}',
            Initial::ImorisoriChiut => '\u{1154}',
            Initial::ImomsoriChiut => '\u{1155}',
            Initial::PhiupPiup => '\u{1156}',
            Initial::KabyounPhiup => '\u{1157}',
            Initial::TuHiut => '\u{1158}',
            Initial::Mokkumongthojimsori => '\u{1159}',
            Initial::KiukTiut => '\u{115A}',
            Initial::NiunSiut => '\u{115B}',
            Initial::NiunJiut => '\u{115C}',
            Initial::NiunHiut => '\u{115D}',
            Initial::TiutRiul => '\u{115E}',
            Initial::TiutMium => '\u{A960}',
            Initial::TiutPiup => '\u{A961}',
            Initial::TiutSiut => '\u{A962}',
            Initial::TiutJiut => '\u{A963}',
            Initial::RiulKiuk => '\u{A964}',
            Initial::RiulTuKiuk => '\u{A965}',
            Initial::RiulTiut => '\u{A966}',
            Initial::RiulTuTiut => '\u{A967}',
            Initial::RiulMium => '\u{A968}',
            Initial::RiulPiup => '\u{A969}',
            Initial::RiulTuPiup => '\u{A96A}',
            Initial::RiulKabyounPiup => '\u{A96B}',
            Initial::RiulSiut => '\u{A96C}',
            Initial::RiulJiut => '\u{A96D}',
            Initial::RiulKhiuk => '\u{A96E}',
            Initial::MiumKiuk => '\u{A96F}',
            Initial::MiumTiut => '\u{A970}',
            Initial::MiumSiut => '\u{A971}',
            Initial::PiupSiutThiut => '\u{A972}',
            Initial::PiupKhiuk => '\u{A973}',
            Initial::PiupHiut => '\u{A974}',
            Initial::TuSiutPiup => '\u{A975}',
            Initial::IungRiul => '\u{A976}',
            Initial::IungHiut => '\u{A977}',
            Initial::TuJiutHiut => '\u{A978}',
            Initial::TuThiut => '\u{A979}',
            Initial::PhiupHiut => '\u{A97A}',
            Initial::HiutSiut => '\u{A97B}',
            Initial::TuMokkumongthojimsori => '\u{A97C}',
        }
    }
}

impl From<Medial> for char {
    fn from(c: Medial) -> Self {
        match c {
            Medial::A => '\u{1161}',
            Medial::Ae => '\u{1162}',
            Medial::Ya => '\u{1163}',
            Medial::Yae => '\u{1164}',
            Medial::Eo => '\u{1165}',
            Medial::E => '\u{1166}',
            Medial::Yeo => '\u{1167}',
            Medial::Ye => '\u{1168}',
            Medial::O => '\u{1169}',
            Medial::Wa => '\u{116A}',
            Medial::Wae => '\u{116B}',
            Medial::Oe => '\u{116C}',
            Medial::Yo => '\u{116D}',
            Medial::U => '\u{116E}',
            Medial::Weo => '\u{116F}',
            Medial::We => '\u{1170}',
            Medial::Wi => '\u{1171}',
            Medial::Yu => '\u{1172}',
            Medial::Eu => '\u{1173}',
            Medial::Yi => '\u{1174}',
            Medial::I => '\u{1175}',
            Medial::AO => '\u{1176}',
            Medial::AU => '\u{1177}',
            Medial::YaO => '\u{1178}',
            Medial::YaYo => '\u{1179}',
            Medial::EoO => '\u{117A}',
            Medial::EoU => '\u{117B}',
            Medial::EoEu => '\u{117C}',
            Medial::YeoO => '\u{117D}',
            Medial::YeoU => '\u{117E}',
            Medial::OEo => '\u{117F}',
            Medial::OE => '\u{1180}',
            Medial::OYe => '\u{1181}',
            Medial::OO => '\u{1182}',
            Medial::OU => '\u{1183}',
            Medial::YoYa => '\u{1184}',
            Medial::YoYae => '\u{1185}',
            Medial::YoYeo => '\u{1186}',
            Medial::YoO => '\u{1187}',
            Medial::YoI => '\u{1188}',
            Medial::UA => '\u{1189}',
            Medial::UAe => '\u{118A}',
            Medial::UEoEu => '\u{118B}',
            Medial::UYe => '\u{118C}',
            Medial::UU => '\u{118D}',
            Medial::YuA => '\u{118E}',
            Medial::YuEo => '\u{118F}',
            Medial::YuE => '\u{1190}',
            Medial::YuYeo => '\u{1191}',
            Medial::YuYe => '\u{1192}',
            Medial::YuU => '\u{1193}',
            Medial::YuI => '\u{1194}',
            Medial::EuU => '\u{1195}',
            Medial::EuEu => '\u{1196}',
            Medial::YiU => '\u{1197}',
            Medial::IA => '\u{1198}',
            Medial::IYa => '\u{1199}',
            Medial::IO => '\u{119A}',
            Medial::IU => '\u{119B}',
            Medial::IEu => '\u{119C}',
            Medial::IAraea => '\u{119D}',
            Medial::Araea => '\u{119E}',
            Medial::AraeaEo => '\u{119F}',
            Medial::AraeaU => '\u{11A0}',
            Medial::AraeaI => '\u{11A1}',
            Medial::TuAraea => '\u{11A2}',
            Medial::AEu => '\u{11A3}',
            Medial::YaU => '\u{11A4}',
            Medial::YeoYa => '\u{11A5}',
            Medial::OYa => '\u{11A6}',
            Medial::OYae => '\u{11A7}',
            Medial::OYeo => '\u{D7B0}',
            Medial::OOI => '\u{D7B1}',
            Medial::YoA => '\u{D7B2}',
            Medial::YoAe => '\u{D7B3}',
            Medial::YoEo => '\u{D7B4}',
            Medial::UYeo => '\u{D7B5}',
            Medial::UII => '\u{D7B6}',
            Medial::YuAe => '\u{D7B7}',
            Medial::YuO => '\u{D7B8}',
            Medial::EuA => '\u{D7B9}',
            Medial::EuEo => '\u{D7BA}',
            Medial::EuE => '\u{D7BB}',
            Medial::EuO => '\u{D7BC}',
            Medial::IYaO => '\u{D7BD}',
            Medial::IYae => '\u{D7BE}',
            Medial::IYeo => '\u{D7BF}',
            Medial::IYe => '\u{D7C0}',
            Medial::IOI => '\u{D7C1}',
            Medial::IYo => '\u{D7C2}',
            Medial::IYu => '\u{D7C3}',
            Medial::II => '\u{D7C4}',
            Medial::AraeaA => '\u{D7C5}',
            Medial::AraeaE => '\u{D7C6}',
        }
    }
}

impl From<Final> for char {
    fn from(c: Final) -> Self {
        match c {
            Final::Kiuk => '\u{11A8}',
            Final::ToenKiuk => '\u{11A9}',
            Final::KiukSiut => '\u{11AA}',
            Final::Niun => '\u{11AB}',
            Final::NiunJiut => '\u{11AC}',
            Final::NiunHiut => '\u{11AD}',
            Final::Tiut => '\u{11AE}',
            Final::Riul => '\u{11AF}',
            Final::RiulKiuk => '\u{11B0}',
            Final::RiulMium => '\u{11B1}',
            Final::RiulPiup => '\u{11B2}',
            Final::RiulSiut => '\u{11B3}',
            Final::RiulThiut => '\u{11B4}',
            Final::RiulPhiup => '\u{11B5}',
            Final::RiulHiut => '\u{11B6}',
            Final::Mium => '\u{11B7}',
            Final::Piup => '\u{11B8}',
            Final::PiupSiut => '\u{11B9}',
            Final::Siut => '\u{11BA}',
            Final::ToenSiut => '\u{11BB}',
            Final::Iung => '\u{11BC}',
            Final::Jiut => '\u{11BD}',
            Final::Chiut => '\u{11BE}',
            Final::Khiuk => '\u{11BF}',
            Final::Thiut => '\u{11C0}',
            Final::Phiup => '\u{11C1}',
            Final::Hiut => '\u{11C2}',
            Final::KiukRiul => '\u{11C3}',
            Final::KiukSiutKiuk => '\u{11C4}',
            Final::NiunKiuk => '\u{11C5}',
            Final::NiunTiut => '\u{11C6}',
            Final::NiunSiut => '\u{11C7}',
            Final::NiunPanisori => '\u{11C8}',
            Final::NiunThiut => '\u{11C9}',
            Final::TiutKiuk => '\u{11CA}',
            Final::TiutRiul => '\u{11CB}',
            Final::RiulKiukSiut => '\u{11CC}',
            Final::RiulNiun => '\u{11CD}',
            Final::RiulTiut => '\u{11CE}',
            Final::RiulTiutHiut => '\u{11CF}',
            Final::TuRiul => '\u{11D0}',
            Final::RiulMiumKiuk => '\u{11D1}',
            Final::RiulMiumSiut => '\u{11D2}',
            Final::RiulPiupSiut => '\u{11D3}',
            Final::RiulPiupHiut => '\u{11D4}',
            Final::RiulKabyounPiup => '\u{11D5}',
            Final::RiulTuSiut => '\u{11D6}',
            Final::RiulPanisori => '\u{11D7}',
            Final::RiulKhiuk => '\u{11D8}',
            Final::RiulMokkumongthojimsori => '\u{11D9}',
            Final::MiumKiuk => '\u{11DA}',
            Final::MiumRiul => '\u{11DB}',
            Final::MiumPiup => '\u{11DC}',
            Final::MiumSiut => '\u{11DD}',
            Final::MiumTuSiut => '\u{11DE}',
            Final::MiumPanisori => '\u{11DF}',
            Final::MiumChiut => '\u{11E0}',
            Final::MiumHiut => '\u{11E1}',
            Final::KabyounMium => '\u{11E2}',
            Final::PiupRiul => '\u{11E3}',
            Final::PiupPhiup => '\u{11E4}',
            Final::PiupHiut => '\u{11E5}',
            Final::KabyounPiup => '\u{11E6}',
            Final::SiutKiuk => '\u{11E7}',
            Final::SiutTiut => '\u{11E8}',
            Final::SiutRiul => '\u{11E9}',
            Final::SiutPiup => '\u{11EA}',
            Final::Panisori => '\u{11EB}',
            Final::IungKiuk => '\u{11EC}',
            Final::IungTuKiuk => '\u{11ED}',
            Final::TuIung => '\u{11EE}',
            Final::IungKhiuk => '\u{11EF}',
            Final::Ogumisori => '\u{11F0}',
            Final::OgumisoriSiut => '\u{11F1}',
            Final::OgumisoriPanisori => '\u{11F2}',
            Final::PhiupPiup => '\u{11F3}',
            Final::KabyounPhiup => '\u{11F4}',
            Final::HiutNiun => '\u{11F5}',
            Final::HiutRiul => '\u{11F6}',
            Final::HiutMium => '\u{11F7}',
            Final::HiutPiup => '\u{11F8}',
            Final::Mokkumongthojimsori => '\u{11F9}',
            Final::KiukNiun => '\u{11FA}',
            Final::KiukPiup => '\u{11FB}',
            Final::KiukChiut => '\u{11FC}',
            Final::KiukKhiuk => '\u{11FD}',
            Final::KiukHiut => '\u{11FE}',
            Final::TuNiun => '\u{11FF}',
            Final::NiunRiul => '\u{D7CB}',
            Final::NiunChiut => '\u{D7CC}',
            Final::TuTiut => '\u{D7CD}',
            Final::TuTiutPiup => '\u{D7CE}',
            Final::TiutPiup => '\u{D7CF}',
            Final::TiutSiut => '\u{D7D0}',
            Final::TiutSiutKiuk => '\u{D7D1}',
            Final::TiutJiut => '\u{D7D2}',
            Final::TiutChiut => '\u{D7D3}',
            Final::TiutThiut => '\u{D7D4}',
            Final::RiulTuKiuk => '\u{D7D5}',
            Final::RiulKiukHiut => '\u{D7D6}',
            Final::TuRiulKhiuk => '\u{D7D7}',
            Final::RiulMiumHiut => '\u{D7D8}',
            Final::RiulPiupTiut => '\u{D7D9}',
            Final::RiulPiupPhiup => '\u{D7DA}',
            Final::RiulOgumisori => '\u{D7DB}',
            Final::RiulMokkumongthojimsoriHiut => '\u{D7DC}',
            Final::KabyounRiul => '\u{D7DD}',
            Final::MiumNiun => '\u{D7DE}',
            Final::MiumTuNiun => '\u{D7DF}',
            Final::TuMium => '\u{D7E0}',
            Final::MiumPiupSiut => '\u{D7E1}',
            Final::MiumJiut => '\u{D7E2}',
            Final::PiupTiut => '\u{D7E3}',
            Final::PiupRiulPhiup => '\u{D7E4}',
            Final::PiupMium => '\u{D7E5}',
            Final::TuPiup => '\u{D7E6}',
            Final::PiupSiutTiut => '\u{D7E7}',
            Final::PiupJiut => '\u{D7E8}',
            Final::PiupChiut => '\u{D7E9}',
            Final::SiutMium => '\u{D7EA}',
            Final::SiutKabyounPiup => '\u{D7EB}',
            Final::TuSiutKiuk => '\u{D7EC}',
            Final::TuSiutTiut => '\u{D7ED}',
            Final::SiutPanisori => '\u{D7EE}',
            Final::SiutJiut => '\u{D7EF}',
            Final::SiutChiut => '\u{D7F0}',
            Final::SiutThiut => '\u{D7F1}',
            Final::SiutHiut => '\u{D7F2}',
            Final::PanisoriPiup => '\u{D7F3}',
            Final::PanisoriKabyounPiup => '\u{D7F4}',
            Final::OgumisoriMium => '\u{D7F5}',
            Final::OgumisoriHiut => '\u{D7F6}',
            Final::JiutPiup => '\u{D7F7}',
            Final::JiutTuPiup => '\u{D7F8}',
            Final::TuJiut => '\u{D7F9}',
            Final::PhiupSiut => '\u{D7FA}',
            Final::PhiupThiut => '\u{D7FB}',
        }
    }
}

impl_jamo!(
    Initial,
    [
        (Kiuk, 'ㄱ'),
        (ToenKiuk, 'ㄲ'),
        (Niun, 'ㄴ'),
        (Tiut, 'ㄷ'),
        (ToenTiut, 'ㄸ'),
        (Riul, 'ㄹ'),
        (Mium, 'ㅁ'),
        (Piup, 'ㅂ'),
        (ToenPiup, 'ㅃ'),
        (Siut, 'ㅅ'),
        (ToenSiut, 'ㅆ'),
        (Iung, 'ㅇ'),
        (Jiut, 'ㅈ'),
        (ToenJiut, 'ㅉ'),
        (Chiut, 'ㅊ'),
        (Khiuk, 'ㅋ'),
        (Thiut, 'ㅌ'),
        (Phiup, 'ㅍ'),
        (Hiut, 'ㅎ'),
        (NiunKiuk, 'ᄓ'),
        (TuNiun, 'ᄔ'),
        (NiunTiut, 'ᄕ'),
        (NiunPiup, 'ᄖ'),
        (TiutKiuk, 'ᄗ'),
        (RiulNiun, 'ᄘ'),
        (TuRiul, 'ᄙ'),
        (RiulHiut, 'ᄚ'),
        (KabyounRiul, 'ᄛ'),
        (MiumPiup, 'ᄜ'),
        (KabyounMium, 'ᄝ'),
        (PiupKiuk, 'ᄞ'),
        (PiupNiun, 'ᄟ'),
        (PiupTiut, 'ᄠ'),
        (PiupSiut, 'ᄡ'),
        (PiupSiutKiuk, 'ᄢ'),
        (PiupSiutTiut, 'ᄣ'),
        (PiupSiutPiup, 'ᄤ'),
        (PiupTuSiut, 'ᄥ'),
        (PiupSiutJiut, 'ᄦ'),
        (PiupJiut, 'ᄧ'),
        (PiupChiut, 'ᄨ'),
        (PiupThiut, 'ᄩ'),
        (PiupPhiup, 'ᄪ'),
        (KabyounPiup, 'ᄫ'),
        (KabyounTuPiup, 'ᄬ'),
        (SiutKiuk, 'ᄭ'),
        (SiutNiun, 'ᄮ'),
        (SiutTiut, 'ᄯ'),
        (SiutRiul, 'ᄰ'),
        (SiutMium, 'ᄱ'),
        (SiutPiup, 'ᄲ'),
        (SiutPiupKiuk, 'ᄳ'),
        (SiutTuSiut, 'ᄴ'),
        (SiutIung, 'ᄵ'),
        (SiutJiut, 'ᄶ'),
        (SiutChiut, 'ᄷ'),
        (SiutKhiuk, 'ᄸ'),
        (SiutThiut, 'ᄹ'),
        (SiutPhiup, 'ᄺ'),
        (SiutHiut, 'ᄻ'),
        (ImorisoriSiut, 'ᄼ'),
        (ImorisoriTuSiut, 'ᄽ'),
        (ImomsoriSiut, 'ᄾ'),
        (ImomsoriTuSiut, 'ᄿ'),
        (Panisori, 'ᅀ'),
        (IungKiuk, 'ᅁ'),
        (IungTiut, 'ᅂ'),
        (IungMium, 'ᅃ'),
        (IungPiup, 'ᅄ'),
        (IungSiut, 'ᅅ'),
        (IungPanisori, 'ᅆ'),
        (TuIung, 'ᅇ'),
        (IungJiut, 'ᅈ'),
        (IungChiut, 'ᅉ'),
        (IungThiut, 'ᅊ'),
        (IungPhiup, 'ᅋ'),
        (Ogumisori, 'ᅌ'),
        (JiutIung, 'ᅍ'),
        (ImorisoriJiut, 'ᅎ'),
        (ImorisoriTuJiut, 'ᅏ'),
        (ImomsoriJiut, 'ᅐ'),
        (ImomsoriTuJiut, 'ᅑ'),
        (ChiutKhiuk, 'ᅒ'),
        (ChiutHiut, 'ᅓ'),
        (ImorisoriChiut, 'ᅔ'),
        (ImomsoriChiut, 'ᅕ'),
        (PhiupPiup, 'ᅖ'),
        (KabyounPhiup, 'ᅗ'),
        (TuHiut, 'ᅘ'),
        (Mokkumongthojimsori, 'ᅙ'),
        (KiukTiut, 'ᅚ'),
        (NiunSiut, 'ᅛ'),
        (NiunJiut, 'ᅜ'),
        (NiunHiut, 'ᅝ'),
        (TiutRiul, 'ᅞ'),
        (TiutMium, 'ꥠ'),
        (TiutPiup, 'ꥡ'),
        (TiutSiut, 'ꥢ'),
        (TiutJiut, 'ꥣ'),
        (RiulKiuk, 'ꥤ'),
        (RiulTuKiuk, 'ꥥ'),
        (RiulTiut, 'ꥦ'),
        (RiulTuTiut, 'ꥧ'),
        (RiulMium, 'ꥨ'),
        (RiulPiup, 'ꥩ'),
        (RiulTuPiup, 'ꥪ'),
        (RiulKabyounPiup, 'ꥫ'),
        (RiulSiut, 'ꥬ'),
        (RiulJiut, 'ꥭ'),
        (RiulKhiuk, 'ꥮ'),
        (MiumKiuk, 'ꥯ'),
        (MiumTiut, 'ꥰ'),
        (MiumSiut, 'ꥱ'),
        (PiupSiutThiut, 'ꥲ'),
        (PiupKhiuk, 'ꥳ'),
        (PiupHiut, 'ꥴ'),
        (TuSiutPiup, 'ꥵ'),
        (IungRiul, 'ꥶ'),
        (IungHiut, 'ꥷ'),
        (TuJiutHiut, 'ꥸ'),
        (TuThiut, 'ꥹ'),
        (PhiupHiut, 'ꥺ'),
        (HiutSiut, 'ꥻ'),
        (TuMokkumongthojimsori, 'ꥼ'),
    ]
);

impl_jamo!(
    Medial,
    [
        (A, 'ㅏ'),
        (Ae, 'ㅐ'),
        (Ya, 'ㅑ'),
        (Yae, 'ㅒ'),
        (Eo, 'ㅓ'),
        (E, 'ㅔ'),
        (Yeo, 'ㅕ'),
        (Ye, 'ㅖ'),
        (O, 'ㅗ'),
        (Wa, 'ㅘ'),
        (Wae, 'ㅙ'),
        (Oe, 'ㅚ'),
        (Yo, 'ㅛ'),
        (U, 'ㅜ'),
        (Weo, 'ㅝ'),
        (We, 'ㅞ'),
        (Wi, 'ㅟ'),
        (Yu, 'ㅠ'),
        (Eu, 'ㅡ'),
        (Yi, 'ㅢ'),
        (I, 'ㅣ'),
        (AO, 'ᅶ'),
        (AU, 'ᅷ'),
        (YaO, 'ᅸ'),
        (YaYo, 'ᅹ'),
        (EoO, 'ᅺ'),
        (EoU, 'ᅻ'),
        (EoEu, 'ᅼ'),
        (YeoO, 'ᅽ'),
        (YeoU, 'ᅾ'),
        (OEo, 'ᅿ'),
        (OE, 'ᆀ'),
        (OYe, 'ᆁ'),
        (OO, 'ᆂ'),
        (OU, 'ᆃ'),
        (YoYa, 'ᆄ'),
        (YoYae, 'ᆅ'),
        (YoYeo, 'ᆆ'),
        (YoO, 'ᆇ'),
        (YoI, 'ᆈ'),
        (UA, 'ᆉ'),
        (UAe, 'ᆊ'),
        (UEoEu, 'ᆋ'),
        (UYe, 'ᆌ'),
        (UU, 'ᆍ'),
        (YuA, 'ᆎ'),
        (YuEo, 'ᆏ'),
        (YuE, 'ᆐ'),
        (YuYeo, 'ᆑ'),
        (YuYe, 'ᆒ'),
        (YuU, 'ᆓ'),
        (YuI, 'ᆔ'),
        (EuU, 'ᆕ'),
        (EuEu, 'ᆖ'),
        (YiU, 'ᆗ'),
        (IA, 'ᆘ'),
        (IYa, 'ᆙ'),
        (IO, 'ᆚ'),
        (IU, 'ᆛ'),
        (IEu, 'ᆜ'),
        (IAraea, 'ᆝ'),
        (Araea, 'ᆞ'),
        (AraeaEo, 'ᆟ'),
        (AraeaU, 'ᆠ'),
        (AraeaI, 'ᆡ'),
        (TuAraea, 'ᆢ'),
        (AEu, 'ᆣ'),
        (YaU, 'ᆤ'),
        (YeoYa, 'ᆥ'),
        (OYa, 'ᆦ'),
        (OYae, 'ᆧ'),
        (OYeo, 'ힰ'),
        (OOI, 'ힱ'),
        (YoA, 'ힲ'),
        (YoAe, 'ힳ'),
        (YoEo, 'ힴ'),
        (UYeo, 'ힵ'),
        (UII, 'ힶ'),
        (YuAe, 'ힷ'),
        (YuO, 'ힸ'),
        (EuA, 'ힹ'),
        (EuEo, 'ힺ'),
        (EuE, 'ힻ'),
        (EuO, 'ힼ'),
        (IYaO, 'ힽ'),
        (IYae, 'ힾ'),
        (IYeo, 'ힿ'),
        (IYe, 'ퟀ'),
        (IOI, 'ퟁ'),
        (IYo, 'ퟂ'),
        (IYu, 'ퟃ'),
        (II, 'ퟄ'),
        (AraeaA, 'ퟅ'),
        (AraeaE, 'ퟆ'),
    ]
);

impl_jamo!(
    Final,
    [
        (Kiuk, 'ㄱ'),
        (ToenKiuk, 'ㄲ'),
        (KiukSiut, 'ㄳ'),
        (Niun, 'ㄴ'),
        (NiunJiut, 'ㄵ'),
        (NiunHiut, 'ㄶ'),
        (Tiut, 'ㄷ'),
        (Riul, 'ㄹ'),
        (RiulKiuk, 'ㄺ'),
        (RiulMium, 'ㄻ'),
        (RiulPiup, 'ㄼ'),
        (RiulSiut, 'ㄽ'),
        (RiulThiut, 'ㄾ'),
        (RiulPhiup, 'ㄿ'),
        (RiulHiut, 'ㅀ'),
        (Mium, 'ㅁ'),
        (Piup, 'ㅂ'),
        (PiupSiut, 'ㅄ'),
        (Siut, 'ㅅ'),
        (ToenSiut, 'ㅆ'),
        (Iung, 'ㅇ'),
        (Jiut, 'ㅈ'),
        (Chiut, 'ㅊ'),
        (Khiuk, 'ㅋ'),
        (Thiut, 'ㅌ'),
        (Phiup, 'ㅍ'),
        (Hiut, 'ㅎ'),
        (KiukRiul, 'ᇃ'),
        (KiukSiutKiuk, 'ᇄ'),
        (NiunKiuk, 'ᇅ'),
        (NiunTiut, 'ᇆ'),
        (NiunSiut, 'ᇇ'),
        (NiunPanisori, 'ᇈ'),
        (NiunThiut, 'ᇉ'),
        (TiutKiuk, 'ᇊ'),
        (TiutRiul, 'ᇋ'),
        (RiulKiukSiut, 'ᇌ'),
        (RiulNiun, 'ᇍ'),
        (RiulTiut, 'ᇎ'),
        (RiulTiutHiut, 'ᇏ'),
        (TuRiul, 'ᇐ'),
        (RiulMiumKiuk, 'ᇑ'),
        (RiulMiumSiut, 'ᇒ'),
        (RiulPiupSiut, 'ᇓ'),
        (RiulPiupHiut, 'ᇔ'),
        (RiulKabyounPiup, 'ᇕ'),
        (RiulTuSiut, 'ᇖ'),
        (RiulPanisori, 'ᇗ'),
        (RiulKhiuk, 'ᇘ'),
        (RiulMokkumongthojimsori, 'ᇙ'),
        (MiumKiuk, 'ᇚ'),
        (MiumRiul, 'ᇛ'),
        (MiumPiup, 'ᇜ'),
        (MiumSiut, 'ᇝ'),
        (MiumTuSiut, 'ᇞ'),
        (MiumPanisori, 'ᇟ'),
        (MiumChiut, 'ᇠ'),
        (MiumHiut, 'ᇡ'),
        (KabyounMium, 'ᇢ'),
        (PiupRiul, 'ᇣ'),
        (PiupPhiup, 'ᇤ'),
        (PiupHiut, 'ᇥ'),
        (KabyounPiup, 'ᇦ'),
        (SiutKiuk, 'ᇧ'),
        (SiutTiut, 'ᇨ'),
        (SiutRiul, 'ᇩ'),
        (SiutPiup, 'ᇪ'),
        (Panisori, 'ᇫ'),
        (IungKiuk, 'ᇬ'),
        (IungTuKiuk, 'ᇭ'),
        (TuIung, 'ᇮ'),
        (IungKhiuk, 'ᇯ'),
        (Ogumisori, 'ᇰ'),
        (OgumisoriSiut, 'ᇱ'),
        (OgumisoriPanisori, 'ᇲ'),
        (PhiupPiup, 'ᇳ'),
        (KabyounPhiup, 'ᇴ'),
        (HiutNiun, 'ᇵ'),
        (HiutRiul, 'ᇶ'),
        (HiutMium, 'ᇷ'),
        (HiutPiup, 'ᇸ'),
        (Mokkumongthojimsori, 'ᇹ'),
        (KiukNiun, 'ᇺ'),
        (KiukPiup, 'ᇻ'),
        (KiukChiut, 'ᇼ'),
        (KiukKhiuk, 'ᇽ'),
        (KiukHiut, 'ᇾ'),
        (TuNiun, 'ᇿ'),
        (NiunRiul, 'ퟋ'),
        (NiunChiut, 'ퟌ'),
        (TuTiut, 'ퟍ'),
        (TuTiutPiup, 'ퟎ'),
        (TiutPiup, 'ퟏ'),
        (TiutSiut, 'ퟐ'),
        (TiutSiutKiuk, 'ퟑ'),
        (TiutJiut, 'ퟒ'),
        (TiutChiut, 'ퟓ'),
        (TiutThiut, 'ퟔ'),
        (RiulTuKiuk, 'ퟕ'),
        (RiulKiukHiut, 'ퟖ'),
        (TuRiulKhiuk, 'ퟗ'),
        (RiulMiumHiut, 'ퟘ'),
        (RiulPiupTiut, 'ퟙ'),
        (RiulPiupPhiup, 'ퟚ'),
        (RiulOgumisori, 'ퟛ'),
        (RiulMokkumongthojimsoriHiut, 'ퟜ'),
        (KabyounRiul, 'ퟝ'),
        (MiumNiun, 'ퟞ'),
        (MiumTuNiun, 'ퟟ'),
        (TuMium, 'ퟠ'),
        (MiumPiupSiut, 'ퟡ'),
        (MiumJiut, 'ퟢ'),
        (PiupTiut, 'ퟣ'),
        (PiupRiulPhiup, 'ퟤ'),
        (PiupMium, 'ퟥ'),
        (TuPiup, 'ퟦ'),
        (PiupSiutTiut, 'ퟧ'),
        (PiupJiut, 'ퟨ'),
        (PiupChiut, 'ퟩ'),
        (SiutMium, 'ퟪ'),
        (SiutKabyounPiup, 'ퟫ'),
        (TuSiutKiuk, 'ퟬ'),
        (TuSiutTiut, 'ퟭ'),
        (SiutPanisori, 'ퟮ'),
        (SiutJiut, 'ퟯ'),
        (SiutChiut, 'ퟰ'),
        (SiutThiut, 'ퟱ'),
        (SiutHiut, 'ퟲ'),
        (PanisoriPiup, 'ퟳ'),
        (PanisoriKabyounPiup, 'ퟴ'),
        (OgumisoriMium, 'ퟵ'),
        (OgumisoriHiut, 'ퟶ'),
        (JiutPiup, 'ퟷ'),
        (JiutTuPiup, 'ퟸ'),
        (TuJiut, 'ퟹ'),
        (PhiupSiut, 'ퟺ'),
        (PhiupThiut, 'ퟻ'),
    ]
);

impl_traits!(Initial, '\u{1100}');
impl_traits!(Medial, '\u{1161}');
impl_traits!(Final, '\u{11A8}');

pub const fn initial_to_final(initial_sound: Initial) -> Option<Final> {
    match initial_sound {
        Initial::Kiuk => Some(Final::Kiuk),
        Initial::ToenKiuk => Some(Final::ToenKiuk),
        Initial::Niun => Some(Final::Niun),
        Initial::Tiut => Some(Final::Tiut),
        Initial::Riul => Some(Final::Riul),
        Initial::Mium => Some(Final::Mium),
        Initial::Piup => Some(Final::Piup),
        Initial::Siut => Some(Final::Siut),
        Initial::ToenSiut => Some(Final::ToenSiut),
        Initial::Iung => Some(Final::Iung),
        Initial::Jiut => Some(Final::Jiut),
        Initial::Chiut => Some(Final::Chiut),
        Initial::Khiuk => Some(Final::Khiuk),
        Initial::Thiut => Some(Final::Thiut),
        Initial::Phiup => Some(Final::Phiup),
        Initial::Hiut => Some(Final::Hiut),
        // Old jamo that have both initial and final variants
        Initial::NiunKiuk => Some(Final::NiunKiuk),
        Initial::TuNiun => Some(Final::TuNiun),
        Initial::NiunTiut => Some(Final::NiunTiut),
        Initial::TiutKiuk => Some(Final::TiutKiuk),
        Initial::RiulNiun => Some(Final::RiulNiun),
        Initial::TuRiul => Some(Final::TuRiul),
        Initial::RiulHiut => Some(Final::RiulHiut),
        Initial::KabyounRiul => Some(Final::KabyounRiul),
        Initial::MiumPiup => Some(Final::MiumPiup),
        Initial::KabyounMium => Some(Final::KabyounMium),
        Initial::PiupTiut => Some(Final::PiupTiut),
        Initial::PiupSiut => Some(Final::PiupSiut),
        Initial::PiupSiutTiut => Some(Final::PiupSiutTiut),
        Initial::PiupJiut => Some(Final::PiupJiut),
        Initial::PiupChiut => Some(Final::PiupChiut),
        Initial::PiupPhiup => Some(Final::PiupPhiup),
        Initial::KabyounPiup => Some(Final::KabyounPiup),
        Initial::SiutKiuk => Some(Final::SiutKiuk),
        Initial::SiutTiut => Some(Final::SiutTiut),
        Initial::SiutRiul => Some(Final::SiutRiul),
        Initial::SiutMium => Some(Final::SiutMium),
        Initial::SiutPiup => Some(Final::SiutPiup),
        Initial::SiutJiut => Some(Final::SiutJiut),
        Initial::SiutChiut => Some(Final::SiutChiut),
        Initial::SiutThiut => Some(Final::SiutThiut),
        Initial::SiutHiut => Some(Final::SiutHiut),
        Initial::Panisori => Some(Final::Panisori),
        Initial::IungKiuk => Some(Final::IungKiuk),
        Initial::TuIung => Some(Final::TuIung),
        Initial::Ogumisori => Some(Final::Ogumisori),
        Initial::PhiupPiup => Some(Final::PhiupPiup),
        Initial::KabyounPhiup => Some(Final::KabyounPhiup),
        Initial::Mokkumongthojimsori => Some(Final::Mokkumongthojimsori),
        Initial::NiunSiut => Some(Final::NiunSiut),
        Initial::NiunJiut => Some(Final::NiunJiut),
        Initial::NiunHiut => Some(Final::NiunHiut),
        Initial::TiutRiul => Some(Final::TiutRiul),
        Initial::TiutPiup => Some(Final::TiutPiup),
        Initial::TiutSiut => Some(Final::TiutSiut),
        Initial::TiutJiut => Some(Final::TiutJiut),
        Initial::RiulKiuk => Some(Final::RiulKiuk),
        Initial::RiulTuKiuk => Some(Final::RiulTuKiuk),
        Initial::RiulTiut => Some(Final::RiulTiut),
        Initial::RiulMium => Some(Final::RiulMium),
        Initial::RiulPiup => Some(Final::RiulPiup),
        Initial::RiulKabyounPiup => Some(Final::RiulKabyounPiup),
        Initial::RiulSiut => Some(Final::RiulSiut),
        Initial::RiulKhiuk => Some(Final::RiulKhiuk),
        Initial::MiumKiuk => Some(Final::MiumKiuk),
        Initial::MiumSiut => Some(Final::MiumSiut),
        Initial::PiupHiut => Some(Final::PiupHiut),
        _ => None,
    }
}

