use enumset::{EnumSet, EnumSetType};
use num_derive::FromPrimitive;
use num_traits::FromPrimitive;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug)]
pub struct InputOptions {
    pub auto_reorder: bool,
    pub combi_on_double_stroke: bool,
    pub non_initial_combi: bool,
    pub medial_combi: bool,
    pub treat_final_as_initial: bool,
    pub old_jamo_mode: bool,
    pub noble_name: bool,
    pub word_unit_commit: bool,
}

impl Default for InputOptions {
    fn default() -> Self {
        Self {
            auto_reorder: false,
            combi_on_double_stroke: false,
            non_initial_combi: false,
            medial_combi: true,
            treat_final_as_initial: true,
            old_jamo_mode: false,
            noble_name: false,
            word_unit_commit: false,
        }
    }
}

#[derive(Hash, Serialize, Deserialize, Debug, EnumSetType)]
#[enumset(serialize_repr = "list")]
pub enum Addon {
    ComposeInitialToen,
    ComposeMedialToen,
    ComposeFinalToen,
    DecomposeInitialToen,
    DecomposeMedialToen,
    DecomposeFinalToen,
    FlexibleComposeOrder,
    TreatFinalAsInitial,
    TreatFinalAsInitialCompose,
}

pub fn default_addons() -> EnumSet<Addon> {
    EnumSet::only(Addon::ComposeInitialToen).union(EnumSet::only(Addon::TreatFinalAsInitial))
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq, Default)]
pub enum PreeditJohabLevel {
    Always,
    #[default]
    Needed,
    Never,
}

macro_rules! impl_jamo {
    ($ty:ty, [$(($item:ident, $ch:expr)),+ $(,)?]) => {
        impl $ty {
            pub const fn jamo(self) -> char {
                match self {
                    $(Self::$item => $ch,)+
                }
            }

            pub const fn from_initial_sound(c: char) -> Option<Self> {
                match c {
                    $($ch => Some(Self::$item),)+
                    _ => None,
                }
            }
        }
    };
}

macro_rules! impl_traits {
    ($ty:ty, $first_ch:expr) => {
        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                write!(f, "{}", char::from(*self))
            }
        }

        impl TryFrom<char> for $ty {
            type Error = ();
            fn try_from(ch: char) -> Result<Self, Self::Error> {
                use std::convert::TryInto;
                (ch as u32).try_into()
            }
        }

        impl TryFrom<u32> for $ty {
            type Error = ();
            fn try_from(n: u32) -> Result<Self, Self::Error> {
                match n.checked_sub($first_ch as u32) {
                    Some(idx) => FromPrimitive::from_u32(idx).ok_or(()),
                    None => Err(()),
                }
            }
        }

        impl Serialize for $ty {
            fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                serializer.serialize_char((*self).into())
            }
        }

        impl<'de> Deserialize<'de> for $ty {
            fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                use serde::de::Error;
                use std::convert::TryInto;
                let ch = char::deserialize(deserializer)?;
                ch.try_into()
                    .map_err(|_| D::Error::custom(format!("Not {}", stringify!($ty))))
            }
        }
    };
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, FromPrimitive)]
#[repr(u32)]
pub enum Initial {
    기윽,
    된기윽,
    니은,
    디읃,
    된디읃,
    리을,
    미음,
    비읍,
    된비읍,
    시읏,
    된시읏,
    이응,
    지읒,
    된지읒,
    치읓,
    키읔,
    티읕,
    피읖,
    히읗,
    니은기윽,
    두니은,
    니은디읃,
    니은비읍,
    디읃기윽,
    리을니은,
    두리을,
    리을히읗,
    가벼운리을,
    미음비읍,
    가벼운미음,
    비읍기윽,
    비읍니은,
    비읍디읃,
    비읍시읏,
    비읍시읏기윽,
    비읍시읏디읃,
    비읍시읏비읍,
    비읍두시읏,
    비읍시읏지읒,
    비읍지읒,
    비읍치읓,
    비읍티읕,
    비읍피읖,
    가벼운비읍,
    가벼운두비읍,
    시읏기윽,
    시읏니은,
    시읏디읃,
    시읏리을,
    시읏미음,
    시읏비읍,
    시읏비읍기윽,
    시읏두시읏,
    시읏이응,
    시읏지읒,
    시읏치읓,
    시읏키읔,
    시읏티읕,
    시읏피읖,
    시읏히읗,
    이머리소리시읏,
    이머리소리두시읏,
    이몸소리시읏,
    이몸소리두시읏,
    반이소리,
    이응기윽,
    이응디읃,
    이응미음,
    이응비읍,
    이응시읏,
    이응반이소리,
    두이응,
    이응지읒,
    이응치읓,
    이응티읕,
    이응피읖,
    어금이소리,
    지읒이응,
    이머리소리지읒,
    이머리소리두지읒,
    이몸소리지읒,
    이몸소리두지읒,
    치읓키읔,
    치읓히읗,
    이머리소리치읓,
    이몸소리치읓,
    피읖비읍,
    가벼운피읖,
    두히읗,
    목구멍터집소리,
    기윽디읃,
    니은시읏,
    니은지읒,
    니은히읗,
    디읃리을,
    디읃미음,
    디읃비읍,
    디읃시읏,
    디읃지읒,
    리을기윽,
    리을두기윽,
    리을디읃,
    리을두디읃,
    리을미음,
    리을비읍,
    리을두비읍,
    리을가벼운비읍,
    리을시읏,
    리을지읒,
    리을키읔,
    미음기윽,
    미음디읃,
    미음시읏,
    비읍시읏티읕,
    비읍키읔,
    비읍히읗,
    두시읏비읍,
    이응리을,
    이응히읗,
    두지읒히읗,
    두티읕,
    피읖히읗,
    히읗시읏,
    두목구멍터집소리,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, FromPrimitive)]
#[repr(u32)]
pub enum Medial {
    A,
    Ae,
    Ya,
    Yae,
    Eo,
    E,
    Yeo,
    Ye,
    O,
    Wa,
    Wae,
    Oe,
    Yo,
    U,
    Weo,
    We,
    Wi,
    Yu,
    Eu,
    Yi,
    I,
    AO,
    AU,
    YaO,
    YaYo,
    EoO,
    EoU,
    EoEu,
    YeoO,
    YeoU,
    OEo,
    OE,
    OYe,
    OO,
    OU,
    YoYa,
    YoYae,
    YoYeo,
    YoO,
    YoI,
    UA,
    UAe,
    UEoEu,
    UYe,
    UU,
    YuA,
    YuEo,
    YuE,
    YuYeo,
    YuYe,
    YuU,
    YuI,
    EuU,
    EuEu,
    YiU,
    IA,
    IYa,
    IO,
    IU,
    IEu,
    IAraea,
    Araea,
    AraeaEo,
    AraeaU,
    AraeaI,
    TuAraea,
    AEu,
    YaU,
    YeoYa,
    OYa,
    OYae,
    OYeo,
    OOI,
    YoA,
    YoAe,
    YoEo,
    UYeo,
    UII,
    YuAe,
    YuO,
    EuA,
    EuEo,
    EuE,
    EuO,
    IYaO,
    IYae,
    IYeo,
    IYe,
    IOI,
    IYo,
    IYu,
    II,
    AraeaA,
    AraeaE,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, FromPrimitive)]
#[repr(u32)]
pub enum Final {
    기윽,
    된기윽,
    기윽시읏,
    니은,
    니은지읒,
    니은히읗,
    디읃,
    리을,
    리을기윽,
    리을미음,
    리을비읍,
    리을시읏,
    리을티읕,
    리을피읖,
    리을히읗,
    미음,
    비읍,
    비읍시읏,
    시읏,
    된시읏,
    이응,
    지읒,
    치읓,
    키읔,
    티읕,
    피읖,
    히읗,
    기윽리을,
    기윽시읏기윽,
    니은기윽,
    니은디읃,
    니은시읏,
    니은반이소리,
    니은티읕,
    디읃기윽,
    디읃리을,
    리을기윽시읏,
    리을니은,
    리을디읃,
    리을디읃히읗,
    두리을,
    리을미음기윽,
    리을미음시읏,
    리을비읍시읏,
    리을비읍히읗,
    리을가벼운비읍,
    리을두시읏,
    리을반이소리,
    리을키읔,
    리을목구멍터집소리,
    미음기윽,
    미음리을,
    미음비읍,
    미음시읏,
    미음두시읏,
    미음반이소리,
    미음치읓,
    미음히읗,
    가벼운미음,
    비읍리을,
    비읍피읖,
    비읍히읗,
    가벼운비읍,
    시읏기윽,
    시읏디읃,
    시읏리을,
    시읏비읍,
    반이소리,
    이응기윽,
    이응두기윽,
    두이응,
    이응키읔,
    어금이소리,
    어금이소리시읏,
    어금이소리반이소리,
    피읖비읍,
    가벼운피읖,
    히읗니은,
    히읗리을,
    히읗미음,
    히읗비읍,
    목구멍터집소리,
    기윽니은,
    기윽비읍,
    기윽치읓,
    기윽키읔,
    기윽히읗,
    두니은,
    니은리을,
    니은치읓,
    두디읃,
    두디읃비읍,
    디읃비읍,
    디읃시읏,
    디읃시읏기윽,
    디읃지읒,
    디읃치읓,
    디읃티읕,
    리을두기윽,
    리을기윽히읗,
    두리을키읔,
    리을미음히읗,
    리을비읍디읃,
    리을비읍피읖,
    리을어금이소리,
    리을목구멍터집소리히읗,
    가벼운리을,
    미음니은,
    미음두니은,
    두미음,
    미음비읍시읏,
    미음지읒,
    비읍디읃,
    비읍리을피읖,
    비읍미음,
    두비읍,
    비읍시읏디읃,
    비읍지읒,
    비읍치읓,
    시읏미음,
    시읏가벼운비읍,
    두시읏기윽,
    두시읏디읃,
    시읏반이소리,
    시읏지읒,
    시읏치읓,
    시읏티읕,
    시읏히읗,
    반이소리비읍,
    반이소리가벼운비읍,
    어금이소리미음,
    어금이소리히읗,
    지읒비읍,
    지읒두비읍,
    두지읒,
    피읖시읏,
    피읖티읕,
}

impl From<Initial> for char {
    fn from(c: Initial) -> Self {
        match c {
            Initial::기윽 => '\u{1100}',
            Initial::된기윽 => '\u{1101}',
            Initial::니은 => '\u{1102}',
            Initial::디읃 => '\u{1103}',
            Initial::된디읃 => '\u{1104}',
            Initial::리을 => '\u{1105}',
            Initial::미음 => '\u{1106}',
            Initial::비읍 => '\u{1107}',
            Initial::된비읍 => '\u{1108}',
            Initial::시읏 => '\u{1109}',
            Initial::된시읏 => '\u{110A}',
            Initial::이응 => '\u{110B}',
            Initial::지읒 => '\u{110C}',
            Initial::된지읒 => '\u{110D}',
            Initial::치읓 => '\u{110E}',
            Initial::키읔 => '\u{110F}',
            Initial::티읕 => '\u{1110}',
            Initial::피읖 => '\u{1111}',
            Initial::히읗 => '\u{1112}',
            Initial::니은기윽 => '\u{1113}',
            Initial::두니은 => '\u{1114}',
            Initial::니은디읃 => '\u{1115}',
            Initial::니은비읍 => '\u{1116}',
            Initial::디읃기윽 => '\u{1117}',
            Initial::리을니은 => '\u{1118}',
            Initial::두리을 => '\u{1119}',
            Initial::리을히읗 => '\u{111A}',
            Initial::가벼운리을 => '\u{111B}',
            Initial::미음비읍 => '\u{111C}',
            Initial::가벼운미음 => '\u{111D}',
            Initial::비읍기윽 => '\u{111E}',
            Initial::비읍니은 => '\u{111F}',
            Initial::비읍디읃 => '\u{1120}',
            Initial::비읍시읏 => '\u{1121}',
            Initial::비읍시읏기윽 => '\u{1122}',
            Initial::비읍시읏디읃 => '\u{1123}',
            Initial::비읍시읏비읍 => '\u{1124}',
            Initial::비읍두시읏 => '\u{1125}',
            Initial::비읍시읏지읒 => '\u{1126}',
            Initial::비읍지읒 => '\u{1127}',
            Initial::비읍치읓 => '\u{1128}',
            Initial::비읍티읕 => '\u{1129}',
            Initial::비읍피읖 => '\u{112A}',
            Initial::가벼운비읍 => '\u{112B}',
            Initial::가벼운두비읍 => '\u{112C}',
            Initial::시읏기윽 => '\u{112D}',
            Initial::시읏니은 => '\u{112E}',
            Initial::시읏디읃 => '\u{112F}',
            Initial::시읏리을 => '\u{1130}',
            Initial::시읏미음 => '\u{1131}',
            Initial::시읏비읍 => '\u{1132}',
            Initial::시읏비읍기윽 => '\u{1133}',
            Initial::시읏두시읏 => '\u{1134}',
            Initial::시읏이응 => '\u{1135}',
            Initial::시읏지읒 => '\u{1136}',
            Initial::시읏치읓 => '\u{1137}',
            Initial::시읏키읔 => '\u{1138}',
            Initial::시읏티읕 => '\u{1139}',
            Initial::시읏피읖 => '\u{113A}',
            Initial::시읏히읗 => '\u{113B}',
            Initial::이머리소리시읏 => '\u{113C}',
            Initial::이머리소리두시읏 => '\u{113D}',
            Initial::이몸소리시읏 => '\u{113E}',
            Initial::이몸소리두시읏 => '\u{113F}',
            Initial::반이소리 => '\u{1140}',
            Initial::이응기윽 => '\u{1141}',
            Initial::이응디읃 => '\u{1142}',
            Initial::이응미음 => '\u{1143}',
            Initial::이응비읍 => '\u{1144}',
            Initial::이응시읏 => '\u{1145}',
            Initial::이응반이소리 => '\u{1146}',
            Initial::두이응 => '\u{1147}',
            Initial::이응지읒 => '\u{1148}',
            Initial::이응치읓 => '\u{1149}',
            Initial::이응티읕 => '\u{114A}',
            Initial::이응피읖 => '\u{114B}',
            Initial::어금이소리 => '\u{114C}',
            Initial::지읒이응 => '\u{114D}',
            Initial::이머리소리지읒 => '\u{114E}',
            Initial::이머리소리두지읒 => '\u{114F}',
            Initial::이몸소리지읒 => '\u{1150}',
            Initial::이몸소리두지읒 => '\u{1151}',
            Initial::치읓키읔 => '\u{1152}',
            Initial::치읓히읗 => '\u{1153}',
            Initial::이머리소리치읓 => '\u{1154}',
            Initial::이몸소리치읓 => '\u{1155}',
            Initial::피읖비읍 => '\u{1156}',
            Initial::가벼운피읖 => '\u{1157}',
            Initial::두히읗 => '\u{1158}',
            Initial::목구멍터집소리 => '\u{1159}',
            Initial::기윽디읃 => '\u{115A}',
            Initial::니은시읏 => '\u{115B}',
            Initial::니은지읒 => '\u{115C}',
            Initial::니은히읗 => '\u{115D}',
            Initial::디읃리을 => '\u{115E}',
            Initial::디읃미음 => '\u{A960}',
            Initial::디읃비읍 => '\u{A961}',
            Initial::디읃시읏 => '\u{A962}',
            Initial::디읃지읒 => '\u{A963}',
            Initial::리을기윽 => '\u{A964}',
            Initial::리을두기윽 => '\u{A965}',
            Initial::리을디읃 => '\u{A966}',
            Initial::리을두디읃 => '\u{A967}',
            Initial::리을미음 => '\u{A968}',
            Initial::리을비읍 => '\u{A969}',
            Initial::리을두비읍 => '\u{A96A}',
            Initial::리을가벼운비읍 => '\u{A96B}',
            Initial::리을시읏 => '\u{A96C}',
            Initial::리을지읒 => '\u{A96D}',
            Initial::리을키읔 => '\u{A96E}',
            Initial::미음기윽 => '\u{A96F}',
            Initial::미음디읃 => '\u{A970}',
            Initial::미음시읏 => '\u{A971}',
            Initial::비읍시읏티읕 => '\u{A972}',
            Initial::비읍키읔 => '\u{A973}',
            Initial::비읍히읗 => '\u{A974}',
            Initial::두시읏비읍 => '\u{A975}',
            Initial::이응리을 => '\u{A976}',
            Initial::이응히읗 => '\u{A977}',
            Initial::두지읒히읗 => '\u{A978}',
            Initial::두티읕 => '\u{A979}',
            Initial::피읖히읗 => '\u{A97A}',
            Initial::히읗시읏 => '\u{A97B}',
            Initial::두목구멍터집소리 => '\u{A97C}',
        }
    }
}

impl From<Medial> for char {
    fn from(c: Medial) -> Self {
        match c {
            Medial::A => '\u{1161}',
            Medial::Ae => '\u{1162}',
            Medial::Ya => '\u{1163}',
            Medial::Yae => '\u{1164}',
            Medial::Eo => '\u{1165}',
            Medial::E => '\u{1166}',
            Medial::Yeo => '\u{1167}',
            Medial::Ye => '\u{1168}',
            Medial::O => '\u{1169}',
            Medial::Wa => '\u{116A}',
            Medial::Wae => '\u{116B}',
            Medial::Oe => '\u{116C}',
            Medial::Yo => '\u{116D}',
            Medial::U => '\u{116E}',
            Medial::Weo => '\u{116F}',
            Medial::We => '\u{1170}',
            Medial::Wi => '\u{1171}',
            Medial::Yu => '\u{1172}',
            Medial::Eu => '\u{1173}',
            Medial::Yi => '\u{1174}',
            Medial::I => '\u{1175}',
            Medial::AO => '\u{1176}',
            Medial::AU => '\u{1177}',
            Medial::YaO => '\u{1178}',
            Medial::YaYo => '\u{1179}',
            Medial::EoO => '\u{117A}',
            Medial::EoU => '\u{117B}',
            Medial::EoEu => '\u{117C}',
            Medial::YeoO => '\u{117D}',
            Medial::YeoU => '\u{117E}',
            Medial::OEo => '\u{117F}',
            Medial::OE => '\u{1180}',
            Medial::OYe => '\u{1181}',
            Medial::OO => '\u{1182}',
            Medial::OU => '\u{1183}',
            Medial::YoYa => '\u{1184}',
            Medial::YoYae => '\u{1185}',
            Medial::YoYeo => '\u{1186}',
            Medial::YoO => '\u{1187}',
            Medial::YoI => '\u{1188}',
            Medial::UA => '\u{1189}',
            Medial::UAe => '\u{118A}',
            Medial::UEoEu => '\u{118B}',
            Medial::UYe => '\u{118C}',
            Medial::UU => '\u{118D}',
            Medial::YuA => '\u{118E}',
            Medial::YuEo => '\u{118F}',
            Medial::YuE => '\u{1190}',
            Medial::YuYeo => '\u{1191}',
            Medial::YuYe => '\u{1192}',
            Medial::YuU => '\u{1193}',
            Medial::YuI => '\u{1194}',
            Medial::EuU => '\u{1195}',
            Medial::EuEu => '\u{1196}',
            Medial::YiU => '\u{1197}',
            Medial::IA => '\u{1198}',
            Medial::IYa => '\u{1199}',
            Medial::IO => '\u{119A}',
            Medial::IU => '\u{119B}',
            Medial::IEu => '\u{119C}',
            Medial::IAraea => '\u{119D}',
            Medial::Araea => '\u{119E}',
            Medial::AraeaEo => '\u{119F}',
            Medial::AraeaU => '\u{11A0}',
            Medial::AraeaI => '\u{11A1}',
            Medial::TuAraea => '\u{11A2}',
            Medial::AEu => '\u{11A3}',
            Medial::YaU => '\u{11A4}',
            Medial::YeoYa => '\u{11A5}',
            Medial::OYa => '\u{11A6}',
            Medial::OYae => '\u{11A7}',
            Medial::OYeo => '\u{D7B0}',
            Medial::OOI => '\u{D7B1}',
            Medial::YoA => '\u{D7B2}',
            Medial::YoAe => '\u{D7B3}',
            Medial::YoEo => '\u{D7B4}',
            Medial::UYeo => '\u{D7B5}',
            Medial::UII => '\u{D7B6}',
            Medial::YuAe => '\u{D7B7}',
            Medial::YuO => '\u{D7B8}',
            Medial::EuA => '\u{D7B9}',
            Medial::EuEo => '\u{D7BA}',
            Medial::EuE => '\u{D7BB}',
            Medial::EuO => '\u{D7BC}',
            Medial::IYaO => '\u{D7BD}',
            Medial::IYae => '\u{D7BE}',
            Medial::IYeo => '\u{D7BF}',
            Medial::IYe => '\u{D7C0}',
            Medial::IOI => '\u{D7C1}',
            Medial::IYo => '\u{D7C2}',
            Medial::IYu => '\u{D7C3}',
            Medial::II => '\u{D7C4}',
            Medial::AraeaA => '\u{D7C5}',
            Medial::AraeaE => '\u{D7C6}',
        }
    }
}

impl From<Final> for char {
    fn from(c: Final) -> Self {
        match c {
            Final::기윽 => '\u{11A8}',
            Final::된기윽 => '\u{11A9}',
            Final::기윽시읏 => '\u{11AA}',
            Final::니은 => '\u{11AB}',
            Final::니은지읒 => '\u{11AC}',
            Final::니은히읗 => '\u{11AD}',
            Final::디읃 => '\u{11AE}',
            Final::리을 => '\u{11AF}',
            Final::리을기윽 => '\u{11B0}',
            Final::리을미음 => '\u{11B1}',
            Final::리을비읍 => '\u{11B2}',
            Final::리을시읏 => '\u{11B3}',
            Final::리을티읕 => '\u{11B4}',
            Final::리을피읖 => '\u{11B5}',
            Final::리을히읗 => '\u{11B6}',
            Final::미음 => '\u{11B7}',
            Final::비읍 => '\u{11B8}',
            Final::비읍시읏 => '\u{11B9}',
            Final::시읏 => '\u{11BA}',
            Final::된시읏 => '\u{11BB}',
            Final::이응 => '\u{11BC}',
            Final::지읒 => '\u{11BD}',
            Final::치읓 => '\u{11BE}',
            Final::키읔 => '\u{11BF}',
            Final::티읕 => '\u{11C0}',
            Final::피읖 => '\u{11C1}',
            Final::히읗 => '\u{11C2}',
            Final::기윽리을 => '\u{11C3}',
            Final::기윽시읏기윽 => '\u{11C4}',
            Final::니은기윽 => '\u{11C5}',
            Final::니은디읃 => '\u{11C6}',
            Final::니은시읏 => '\u{11C7}',
            Final::니은반이소리 => '\u{11C8}',
            Final::니은티읕 => '\u{11C9}',
            Final::디읃기윽 => '\u{11CA}',
            Final::디읃리을 => '\u{11CB}',
            Final::리을기윽시읏 => '\u{11CC}',
            Final::리을니은 => '\u{11CD}',
            Final::리을디읃 => '\u{11CE}',
            Final::리을디읃히읗 => '\u{11CF}',
            Final::두리을 => '\u{11D0}',
            Final::리을미음기윽 => '\u{11D1}',
            Final::리을미음시읏 => '\u{11D2}',
            Final::리을비읍시읏 => '\u{11D3}',
            Final::리을비읍히읗 => '\u{11D4}',
            Final::리을가벼운비읍 => '\u{11D5}',
            Final::리을두시읏 => '\u{11D6}',
            Final::리을반이소리 => '\u{11D7}',
            Final::리을키읔 => '\u{11D8}',
            Final::리을목구멍터집소리 => '\u{11D9}',
            Final::미음기윽 => '\u{11DA}',
            Final::미음리을 => '\u{11DB}',
            Final::미음비읍 => '\u{11DC}',
            Final::미음시읏 => '\u{11DD}',
            Final::미음두시읏 => '\u{11DE}',
            Final::미음반이소리 => '\u{11DF}',
            Final::미음치읓 => '\u{11E0}',
            Final::미음히읗 => '\u{11E1}',
            Final::가벼운미음 => '\u{11E2}',
            Final::비읍리을 => '\u{11E3}',
            Final::비읍피읖 => '\u{11E4}',
            Final::비읍히읗 => '\u{11E5}',
            Final::가벼운비읍 => '\u{11E6}',
            Final::시읏기윽 => '\u{11E7}',
            Final::시읏디읃 => '\u{11E8}',
            Final::시읏리을 => '\u{11E9}',
            Final::시읏비읍 => '\u{11EA}',
            Final::반이소리 => '\u{11EB}',
            Final::이응기윽 => '\u{11EC}',
            Final::이응두기윽 => '\u{11ED}',
            Final::두이응 => '\u{11EE}',
            Final::이응키읔 => '\u{11EF}',
            Final::어금이소리 => '\u{11F0}',
            Final::어금이소리시읏 => '\u{11F1}',
            Final::어금이소리반이소리 => '\u{11F2}',
            Final::피읖비읍 => '\u{11F3}',
            Final::가벼운피읖 => '\u{11F4}',
            Final::히읗니은 => '\u{11F5}',
            Final::히읗리을 => '\u{11F6}',
            Final::히읗미음 => '\u{11F7}',
            Final::히읗비읍 => '\u{11F8}',
            Final::목구멍터집소리 => '\u{11F9}',
            Final::기윽니은 => '\u{11FA}',
            Final::기윽비읍 => '\u{11FB}',
            Final::기윽치읓 => '\u{11FC}',
            Final::기윽키읔 => '\u{11FD}',
            Final::기윽히읗 => '\u{11FE}',
            Final::두니은 => '\u{11FF}',
            Final::니은리을 => '\u{D7CB}',
            Final::니은치읓 => '\u{D7CC}',
            Final::두디읃 => '\u{D7CD}',
            Final::두디읃비읍 => '\u{D7CE}',
            Final::디읃비읍 => '\u{D7CF}',
            Final::디읃시읏 => '\u{D7D0}',
            Final::디읃시읏기윽 => '\u{D7D1}',
            Final::디읃지읒 => '\u{D7D2}',
            Final::디읃치읓 => '\u{D7D3}',
            Final::디읃티읕 => '\u{D7D4}',
            Final::리을두기윽 => '\u{D7D5}',
            Final::리을기윽히읗 => '\u{D7D6}',
            Final::두리을키읔 => '\u{D7D7}',
            Final::리을미음히읗 => '\u{D7D8}',
            Final::리을비읍디읃 => '\u{D7D9}',
            Final::리을비읍피읖 => '\u{D7DA}',
            Final::리을어금이소리 => '\u{D7DB}',
            Final::리을목구멍터집소리히읗 => '\u{D7DC}',
            Final::가벼운리을 => '\u{D7DD}',
            Final::미음니은 => '\u{D7DE}',
            Final::미음두니은 => '\u{D7DF}',
            Final::두미음 => '\u{D7E0}',
            Final::미음비읍시읏 => '\u{D7E1}',
            Final::미음지읒 => '\u{D7E2}',
            Final::비읍디읃 => '\u{D7E3}',
            Final::비읍리을피읖 => '\u{D7E4}',
            Final::비읍미음 => '\u{D7E5}',
            Final::두비읍 => '\u{D7E6}',
            Final::비읍시읏디읃 => '\u{D7E7}',
            Final::비읍지읒 => '\u{D7E8}',
            Final::비읍치읓 => '\u{D7E9}',
            Final::시읏미음 => '\u{D7EA}',
            Final::시읏가벼운비읍 => '\u{D7EB}',
            Final::두시읏기윽 => '\u{D7EC}',
            Final::두시읏디읃 => '\u{D7ED}',
            Final::시읏반이소리 => '\u{D7EE}',
            Final::시읏지읒 => '\u{D7EF}',
            Final::시읏치읓 => '\u{D7F0}',
            Final::시읏티읕 => '\u{D7F1}',
            Final::시읏히읗 => '\u{D7F2}',
            Final::반이소리비읍 => '\u{D7F3}',
            Final::반이소리가벼운비읍 => '\u{D7F4}',
            Final::어금이소리미음 => '\u{D7F5}',
            Final::어금이소리히읗 => '\u{D7F6}',
            Final::지읒비읍 => '\u{D7F7}',
            Final::지읒두비읍 => '\u{D7F8}',
            Final::두지읒 => '\u{D7F9}',
            Final::피읖시읏 => '\u{D7FA}',
            Final::피읖티읕 => '\u{D7FB}',
        }
    }
}

impl_jamo!(
    Initial,
    [
        (기윽, 'ㄱ'),
        (된기윽, 'ㄲ'),
        (니은, 'ㄴ'),
        (디읃, 'ㄷ'),
        (된디읃, 'ㄸ'),
        (리을, 'ㄹ'),
        (미음, 'ㅁ'),
        (비읍, 'ㅂ'),
        (된비읍, 'ㅃ'),
        (시읏, 'ㅅ'),
        (된시읏, 'ㅆ'),
        (이응, 'ㅇ'),
        (지읒, 'ㅈ'),
        (된지읒, 'ㅉ'),
        (치읓, 'ㅊ'),
        (키읔, 'ㅋ'),
        (티읕, 'ㅌ'),
        (피읖, 'ㅍ'),
        (히읗, 'ㅎ'),
        (니은기윽, 'ᄓ'),
        (두니은, 'ᄔ'),
        (니은디읃, 'ᄕ'),
        (니은비읍, 'ᄖ'),
        (디읃기윽, 'ᄗ'),
        (리을니은, 'ᄘ'),
        (두리을, 'ᄙ'),
        (리을히읗, 'ᄚ'),
        (가벼운리을, 'ᄛ'),
        (미음비읍, 'ᄜ'),
        (가벼운미음, 'ᄝ'),
        (비읍기윽, 'ᄞ'),
        (비읍니은, 'ᄟ'),
        (비읍디읃, 'ᄠ'),
        (비읍시읏, 'ᄡ'),
        (비읍시읏기윽, 'ᄢ'),
        (비읍시읏디읃, 'ᄣ'),
        (비읍시읏비읍, 'ᄤ'),
        (비읍두시읏, 'ᄥ'),
        (비읍시읏지읒, 'ᄦ'),
        (비읍지읒, 'ᄧ'),
        (비읍치읓, 'ᄨ'),
        (비읍티읕, 'ᄩ'),
        (비읍피읖, 'ᄪ'),
        (가벼운비읍, 'ᄫ'),
        (가벼운두비읍, 'ᄬ'),
        (시읏기윽, 'ᄭ'),
        (시읏니은, 'ᄮ'),
        (시읏디읃, 'ᄯ'),
        (시읏리을, 'ᄰ'),
        (시읏미음, 'ᄱ'),
        (시읏비읍, 'ᄲ'),
        (시읏비읍기윽, 'ᄳ'),
        (시읏두시읏, 'ᄴ'),
        (시읏이응, 'ᄵ'),
        (시읏지읒, 'ᄶ'),
        (시읏치읓, 'ᄷ'),
        (시읏키읔, 'ᄸ'),
        (시읏티읕, 'ᄹ'),
        (시읏피읖, 'ᄺ'),
        (시읏히읗, 'ᄻ'),
        (이머리소리시읏, 'ᄼ'),
        (이머리소리두시읏, 'ᄽ'),
        (이몸소리시읏, 'ᄾ'),
        (이몸소리두시읏, 'ᄿ'),
        (반이소리, 'ᅀ'),
        (이응기윽, 'ᅁ'),
        (이응디읃, 'ᅂ'),
        (이응미음, 'ᅃ'),
        (이응비읍, 'ᅄ'),
        (이응시읏, 'ᅅ'),
        (이응반이소리, 'ᅆ'),
        (두이응, 'ᅇ'),
        (이응지읒, 'ᅈ'),
        (이응치읓, 'ᅉ'),
        (이응티읕, 'ᅊ'),
        (이응피읖, 'ᅋ'),
        (어금이소리, 'ᅌ'),
        (지읒이응, 'ᅍ'),
        (이머리소리지읒, 'ᅎ'),
        (이머리소리두지읒, 'ᅏ'),
        (이몸소리지읒, 'ᅐ'),
        (이몸소리두지읒, 'ᅑ'),
        (치읓키읔, 'ᅒ'),
        (치읓히읗, 'ᅓ'),
        (이머리소리치읓, 'ᅔ'),
        (이몸소리치읓, 'ᅕ'),
        (피읖비읍, 'ᅖ'),
        (가벼운피읖, 'ᅗ'),
        (두히읗, 'ᅘ'),
        (목구멍터집소리, 'ᅙ'),
        (기윽디읃, 'ᅚ'),
        (니은시읏, 'ᅛ'),
        (니은지읒, 'ᅜ'),
        (니은히읗, 'ᅝ'),
        (디읃리을, 'ᅞ'),
        (디읃미음, 'ꥠ'),
        (디읃비읍, 'ꥡ'),
        (디읃시읏, 'ꥢ'),
        (디읃지읒, 'ꥣ'),
        (리을기윽, 'ꥤ'),
        (리을두기윽, 'ꥥ'),
        (리을디읃, 'ꥦ'),
        (리을두디읃, 'ꥧ'),
        (리을미음, 'ꥨ'),
        (리을비읍, 'ꥩ'),
        (리을두비읍, 'ꥪ'),
        (리을가벼운비읍, 'ꥫ'),
        (리을시읏, 'ꥬ'),
        (리을지읒, 'ꥭ'),
        (리을키읔, 'ꥮ'),
        (미음기윽, 'ꥯ'),
        (미음디읃, 'ꥰ'),
        (미음시읏, 'ꥱ'),
        (비읍시읏티읕, 'ꥲ'),
        (비읍키읔, 'ꥳ'),
        (비읍히읗, 'ꥴ'),
        (두시읏비읍, 'ꥵ'),
        (이응리을, 'ꥶ'),
        (이응히읗, 'ꥷ'),
        (두지읒히읗, 'ꥸ'),
        (두티읕, 'ꥹ'),
        (피읖히읗, 'ꥺ'),
        (히읗시읏, 'ꥻ'),
        (두목구멍터집소리, 'ꥼ'),
    ]
);

impl_jamo!(
    Medial,
    [
        (A, 'ㅏ'),
        (Ae, 'ㅐ'),
        (Ya, 'ㅑ'),
        (Yae, 'ㅒ'),
        (Eo, 'ㅓ'),
        (E, 'ㅔ'),
        (Yeo, 'ㅕ'),
        (Ye, 'ㅖ'),
        (O, 'ㅗ'),
        (Wa, 'ㅘ'),
        (Wae, 'ㅙ'),
        (Oe, 'ㅚ'),
        (Yo, 'ㅛ'),
        (U, 'ㅜ'),
        (Weo, 'ㅝ'),
        (We, 'ㅞ'),
        (Wi, 'ㅟ'),
        (Yu, 'ㅠ'),
        (Eu, 'ㅡ'),
        (Yi, 'ㅢ'),
        (I, 'ㅣ'),
        (AO, 'ᅶ'),
        (AU, 'ᅷ'),
        (YaO, 'ᅸ'),
        (YaYo, 'ᅹ'),
        (EoO, 'ᅺ'),
        (EoU, 'ᅻ'),
        (EoEu, 'ᅼ'),
        (YeoO, 'ᅽ'),
        (YeoU, 'ᅾ'),
        (OEo, 'ᅿ'),
        (OE, 'ᆀ'),
        (OYe, 'ᆁ'),
        (OO, 'ᆂ'),
        (OU, 'ᆃ'),
        (YoYa, 'ᆄ'),
        (YoYae, 'ᆅ'),
        (YoYeo, 'ᆆ'),
        (YoO, 'ᆇ'),
        (YoI, 'ᆈ'),
        (UA, 'ᆉ'),
        (UAe, 'ᆊ'),
        (UEoEu, 'ᆋ'),
        (UYe, 'ᆌ'),
        (UU, 'ᆍ'),
        (YuA, 'ᆎ'),
        (YuEo, 'ᆏ'),
        (YuE, 'ᆐ'),
        (YuYeo, 'ᆑ'),
        (YuYe, 'ᆒ'),
        (YuU, 'ᆓ'),
        (YuI, 'ᆔ'),
        (EuU, 'ᆕ'),
        (EuEu, 'ᆖ'),
        (YiU, 'ᆗ'),
        (IA, 'ᆘ'),
        (IYa, 'ᆙ'),
        (IO, 'ᆚ'),
        (IU, 'ᆛ'),
        (IEu, 'ᆜ'),
        (IAraea, 'ᆝ'),
        (Araea, 'ᆞ'),
        (AraeaEo, 'ᆟ'),
        (AraeaU, 'ᆠ'),
        (AraeaI, 'ᆡ'),
        (TuAraea, 'ᆢ'),
        (AEu, 'ᆣ'),
        (YaU, 'ᆤ'),
        (YeoYa, 'ᆥ'),
        (OYa, 'ᆦ'),
        (OYae, 'ᆧ'),
        (OYeo, 'ힰ'),
        (OOI, 'ힱ'),
        (YoA, 'ힲ'),
        (YoAe, 'ힳ'),
        (YoEo, 'ힴ'),
        (UYeo, 'ힵ'),
        (UII, 'ힶ'),
        (YuAe, 'ힷ'),
        (YuO, 'ힸ'),
        (EuA, 'ힹ'),
        (EuEo, 'ힺ'),
        (EuE, 'ힻ'),
        (EuO, 'ힼ'),
        (IYaO, 'ힽ'),
        (IYae, 'ힾ'),
        (IYeo, 'ힿ'),
        (IYe, 'ퟀ'),
        (IOI, 'ퟁ'),
        (IYo, 'ퟂ'),
        (IYu, 'ퟃ'),
        (II, 'ퟄ'),
        (AraeaA, 'ퟅ'),
        (AraeaE, 'ퟆ'),
    ]
);

impl_jamo!(
    Final,
    [
        (기윽, 'ㄱ'),
        (된기윽, 'ㄲ'),
        (기윽시읏, 'ㄳ'),
        (니은, 'ㄴ'),
        (니은지읒, 'ㄵ'),
        (니은히읗, 'ㄶ'),
        (디읃, 'ㄷ'),
        (리을, 'ㄹ'),
        (리을기윽, 'ㄺ'),
        (리을미음, 'ㄻ'),
        (리을비읍, 'ㄼ'),
        (리을시읏, 'ㄽ'),
        (리을티읕, 'ㄾ'),
        (리을피읖, 'ㄿ'),
        (리을히읗, 'ㅀ'),
        (미음, 'ㅁ'),
        (비읍, 'ㅂ'),
        (비읍시읏, 'ㅄ'),
        (시읏, 'ㅅ'),
        (된시읏, 'ㅆ'),
        (이응, 'ㅇ'),
        (지읒, 'ㅈ'),
        (치읓, 'ㅊ'),
        (키읔, 'ㅋ'),
        (티읕, 'ㅌ'),
        (피읖, 'ㅍ'),
        (히읗, 'ㅎ'),
        (기윽리을, 'ᇃ'),
        (기윽시읏기윽, 'ᇄ'),
        (니은기윽, 'ᇅ'),
        (니은디읃, 'ᇆ'),
        (니은시읏, 'ᇇ'),
        (니은반이소리, 'ᇈ'),
        (니은티읕, 'ᇉ'),
        (디읃기윽, 'ᇊ'),
        (디읃리을, 'ᇋ'),
        (리을기윽시읏, 'ᇌ'),
        (리을니은, 'ᇍ'),
        (리을디읃, 'ᇎ'),
        (리을디읃히읗, 'ᇏ'),
        (두리을, 'ᇐ'),
        (리을미음기윽, 'ᇑ'),
        (리을미음시읏, 'ᇒ'),
        (리을비읍시읏, 'ᇓ'),
        (리을비읍히읗, 'ᇔ'),
        (리을가벼운비읍, 'ᇕ'),
        (리을두시읏, 'ᇖ'),
        (리을반이소리, 'ᇗ'),
        (리을키읔, 'ᇘ'),
        (리을목구멍터집소리, 'ᇙ'),
        (미음기윽, 'ᇚ'),
        (미음리을, 'ᇛ'),
        (미음비읍, 'ᇜ'),
        (미음시읏, 'ᇝ'),
        (미음두시읏, 'ᇞ'),
        (미음반이소리, 'ᇟ'),
        (미음치읓, 'ᇠ'),
        (미음히읗, 'ᇡ'),
        (가벼운미음, 'ᇢ'),
        (비읍리을, 'ᇣ'),
        (비읍피읖, 'ᇤ'),
        (비읍히읗, 'ᇥ'),
        (가벼운비읍, 'ᇦ'),
        (시읏기윽, 'ᇧ'),
        (시읏디읃, 'ᇨ'),
        (시읏리을, 'ᇩ'),
        (시읏비읍, 'ᇪ'),
        (반이소리, 'ᇫ'),
        (이응기윽, 'ᇬ'),
        (이응두기윽, 'ᇭ'),
        (두이응, 'ᇮ'),
        (이응키읔, 'ᇯ'),
        (어금이소리, 'ᇰ'),
        (어금이소리시읏, 'ᇱ'),
        (어금이소리반이소리, 'ᇲ'),
        (피읖비읍, 'ᇳ'),
        (가벼운피읖, 'ᇴ'),
        (히읗니은, 'ᇵ'),
        (히읗리을, 'ᇶ'),
        (히읗미음, 'ᇷ'),
        (히읗비읍, 'ᇸ'),
        (목구멍터집소리, 'ᇹ'),
        (기윽니은, 'ᇺ'),
        (기윽비읍, 'ᇻ'),
        (기윽치읓, 'ᇼ'),
        (기윽키읔, 'ᇽ'),
        (기윽히읗, 'ᇾ'),
        (두니은, 'ᇿ'),
        (니은리을, 'ퟋ'),
        (니은치읓, 'ퟌ'),
        (두디읃, 'ퟍ'),
        (두디읃비읍, 'ퟎ'),
        (디읃비읍, 'ퟏ'),
        (디읃시읏, 'ퟐ'),
        (디읃시읏기윽, 'ퟑ'),
        (디읃지읒, 'ퟒ'),
        (디읃치읓, 'ퟓ'),
        (디읃티읕, 'ퟔ'),
        (리을두기윽, 'ퟕ'),
        (리을기윽히읗, 'ퟖ'),
        (두리을키읔, 'ퟗ'),
        (리을미음히읗, 'ퟘ'),
        (리을비읍디읃, 'ퟙ'),
        (리을비읍피읖, 'ퟚ'),
        (리을어금이소리, 'ퟛ'),
        (리을목구멍터집소리히읗, 'ퟜ'),
        (가벼운리을, 'ퟝ'),
        (미음니은, 'ퟞ'),
        (미음두니은, 'ퟟ'),
        (두미음, 'ퟠ'),
        (미음비읍시읏, 'ퟡ'),
        (미음지읒, 'ퟢ'),
        (비읍디읃, 'ퟣ'),
        (비읍리을피읖, 'ퟤ'),
        (비읍미음, 'ퟥ'),
        (두비읍, 'ퟦ'),
        (비읍시읏디읃, 'ퟧ'),
        (비읍지읒, 'ퟨ'),
        (비읍치읓, 'ퟩ'),
        (시읏미음, 'ퟪ'),
        (시읏가벼운비읍, 'ퟫ'),
        (두시읏기윽, 'ퟬ'),
        (두시읏디읃, 'ퟭ'),
        (시읏반이소리, 'ퟮ'),
        (시읏지읒, 'ퟯ'),
        (시읏치읓, 'ퟰ'),
        (시읏티읕, 'ퟱ'),
        (시읏히읗, 'ퟲ'),
        (반이소리비읍, 'ퟳ'),
        (반이소리가벼운비읍, 'ퟴ'),
        (어금이소리미음, 'ퟵ'),
        (어금이소리히읗, 'ퟶ'),
        (지읒비읍, 'ퟷ'),
        (지읒두비읍, 'ퟸ'),
        (두지읒, 'ퟹ'),
        (피읖시읏, 'ퟺ'),
        (피읖티읕, 'ퟻ'),
    ]
);

impl_traits!(Initial, '\u{1100}');
impl_traits!(Medial, '\u{1161}');
impl_traits!(Final, '\u{11A8}');

pub const fn initial_to_final(initial_sound: Initial) -> Option<Final> {
    match initial_sound {
        Initial::기윽 => Some(Final::기윽),
        Initial::된기윽 => Some(Final::된기윽),
        Initial::니은 => Some(Final::니은),
        Initial::디읃 => Some(Final::디읃),
        Initial::리을 => Some(Final::리을),
        Initial::미음 => Some(Final::미음),
        Initial::비읍 => Some(Final::비읍),
        Initial::시읏 => Some(Final::시읏),
        Initial::된시읏 => Some(Final::된시읏),
        Initial::이응 => Some(Final::이응),
        Initial::지읒 => Some(Final::지읒),
        Initial::치읓 => Some(Final::치읓),
        Initial::키읔 => Some(Final::키읔),
        Initial::티읕 => Some(Final::티읕),
        Initial::피읖 => Some(Final::피읖),
        Initial::히읗 => Some(Final::히읗),
        // Old jamo that have both initial and final variants
        Initial::니은기윽 => Some(Final::니은기윽),
        Initial::두니은 => Some(Final::두니은),
        Initial::니은디읃 => Some(Final::니은디읃),
        Initial::디읃기윽 => Some(Final::디읃기윽),
        Initial::리을니은 => Some(Final::리을니은),
        Initial::두리을 => Some(Final::두리을),
        Initial::리을히읗 => Some(Final::리을히읗),
        Initial::가벼운리을 => Some(Final::가벼운리을),
        Initial::미음비읍 => Some(Final::미음비읍),
        Initial::가벼운미음 => Some(Final::가벼운미음),
        Initial::비읍디읃 => Some(Final::비읍디읃),
        Initial::비읍시읏 => Some(Final::비읍시읏),
        Initial::비읍시읏디읃 => Some(Final::비읍시읏디읃),
        Initial::비읍지읒 => Some(Final::비읍지읒),
        Initial::비읍치읓 => Some(Final::비읍치읓),
        Initial::비읍피읖 => Some(Final::비읍피읖),
        Initial::가벼운비읍 => Some(Final::가벼운비읍),
        Initial::시읏기윽 => Some(Final::시읏기윽),
        Initial::시읏디읃 => Some(Final::시읏디읃),
        Initial::시읏리을 => Some(Final::시읏리을),
        Initial::시읏미음 => Some(Final::시읏미음),
        Initial::시읏비읍 => Some(Final::시읏비읍),
        Initial::시읏지읒 => Some(Final::시읏지읒),
        Initial::시읏치읓 => Some(Final::시읏치읓),
        Initial::시읏티읕 => Some(Final::시읏티읕),
        Initial::시읏히읗 => Some(Final::시읏히읗),
        Initial::반이소리 => Some(Final::반이소리),
        Initial::이응기윽 => Some(Final::이응기윽),
        Initial::두이응 => Some(Final::두이응),
        Initial::어금이소리 => Some(Final::어금이소리),
        Initial::피읖비읍 => Some(Final::피읖비읍),
        Initial::가벼운피읖 => Some(Final::가벼운피읖),
        Initial::목구멍터집소리 => Some(Final::목구멍터집소리),
        Initial::니은시읏 => Some(Final::니은시읏),
        Initial::니은지읒 => Some(Final::니은지읒),
        Initial::니은히읗 => Some(Final::니은히읗),
        Initial::디읃리을 => Some(Final::디읃리을),
        Initial::디읃비읍 => Some(Final::디읃비읍),
        Initial::디읃시읏 => Some(Final::디읃시읏),
        Initial::디읃지읒 => Some(Final::디읃지읒),
        Initial::리을기윽 => Some(Final::리을기윽),
        Initial::리을두기윽 => Some(Final::리을두기윽),
        Initial::리을디읃 => Some(Final::리을디읃),
        Initial::리을미음 => Some(Final::리을미음),
        Initial::리을비읍 => Some(Final::리을비읍),
        Initial::리을가벼운비읍 => Some(Final::리을가벼운비읍),
        Initial::리을시읏 => Some(Final::리을시읏),
        Initial::리을키읔 => Some(Final::리을키읔),
        Initial::미음기윽 => Some(Final::미음기윽),
        Initial::미음시읏 => Some(Final::미음시읏),
        Initial::비읍히읗 => Some(Final::비읍히읗),
        _ => None,
    }
}
